-- P3.4a — Field-level KYC verification (Option A) + entity/GST-reg-type on partner.
-- Additive only. Guarded to gifsy_dev. Applied out-of-band via `prisma db execute`
-- (this dev DB is db-push managed, no _prisma_migrations history — never migrate dev).
-- Generated by `prisma migrate diff --from-config-datasource --to-schema` (2026-06-16),
-- reviewed in docs/plans/reconcile/P3-onboarding-kyc.md §4/§9.

BEGIN;
DO $$ BEGIN
  IF current_database() <> 'gifsy_dev' THEN
    RAISE EXCEPTION 'Refusing to run: expected gifsy_dev, got %', current_database();
  END IF;
END $$;

-- CreateEnum
CREATE TYPE "KycFieldKey" AS ENUM ('PAYMENT', 'GST_VALIDATION', 'GST_DOCUMENT', 'ADDRESS', 'ADDRESS_DOCUMENT', 'BOARD_PHOTO', 'OWNER_PHOTO');
CREATE TYPE "KycFieldDecision" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "KycFieldSource" AS ENUM ('EXCEL', 'PORTAL');
CREATE TYPE "EntityType" AS ENUM ('INDIVIDUAL', 'HUF', 'COMPANY', 'FIRM', 'LLP', 'OTHERS');
CREATE TYPE "GstRegistrationType" AS ENUM ('REGULAR', 'COMPOSITE', 'UNREGISTERED');

-- AlterTable
ALTER TABLE "channel_partners"
  ADD COLUMN "entityType" "EntityType",
  ADD COLUMN "gstRegistrationType" "GstRegistrationType";

-- CreateTable
CREATE TABLE "kyc_verification_items" (
    "id" TEXT NOT NULL,
    "kycSubmissionId" TEXT NOT NULL,
    "fieldKey" "KycFieldKey" NOT NULL,
    "decision" "KycFieldDecision" NOT NULL DEFAULT 'PENDING',
    "source" "KycFieldSource",
    "remark" TEXT,
    "verifiedById" TEXT,
    "verifiedAt" TIMESTAMP(3),
    "evidence" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kyc_verification_items_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "kyc_verification_items_kycSubmissionId_idx" ON "kyc_verification_items"("kycSubmissionId");
CREATE INDEX "kyc_verification_items_decision_idx" ON "kyc_verification_items"("decision");
CREATE UNIQUE INDEX "kyc_verification_items_kycSubmissionId_fieldKey_key" ON "kyc_verification_items"("kycSubmissionId", "fieldKey");

-- AddForeignKey
ALTER TABLE "kyc_verification_items" ADD CONSTRAINT "kyc_verification_items_kycSubmissionId_fkey" FOREIGN KEY ("kycSubmissionId") REFERENCES "kyc_submissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
