-- P4 — DROP the World-A SchemeTarget model. DESTRUCTIVE. Guarded to gifsy_dev.
-- Applied out-of-band via `prisma db execute` (db-push managed dev DB; never
-- `prisma migrate dev`). DDL generated by `prisma migrate diff --from-schema
-- <HEAD baseline> --to-schema prisma/schema.prisma --script` (2026-06-17); guard
-- (BEGIN/DO/COMMIT) hand-added per project convention.
--
-- Safe to drop now: SchemeTarget had two readers, both removed —
--   • schemes module getSchemeTarget/listTargets (P4.1)
--   • partner.service "my targets" view, rewired to OutletTarget/OutletSalesRecord (P4.5)
-- grep-confirmed zero `prisma.schemeTarget` readers remain in api/src. Targets are
-- NOT scheme-scoped (schemes ⟂ targets) — see reconcile/P4-programs-targets-enrollment.md.
-- The table is expected EMPTY on gifsy_dev (greenfield World-A leftover).

BEGIN;
DO $$ BEGIN
  IF current_database() <> 'gifsy_dev' THEN
    RAISE EXCEPTION 'Refusing to run: expected gifsy_dev, got %', current_database();
  END IF;
END $$;

-- DropForeignKey
ALTER TABLE "scheme_targets" DROP CONSTRAINT "scheme_targets_schemeId_fkey";

-- DropForeignKey
ALTER TABLE "scheme_targets" DROP CONSTRAINT "scheme_targets_userId_fkey";

-- DropTable
DROP TABLE "scheme_targets";

COMMIT;
