-- P4 (Targets + Enrollment) — ADDITIVE migration. Guarded to gifsy_dev. Applied
-- out-of-band via `prisma db execute` (this dev DB is db-push managed, no
-- _prisma_migrations history — never `prisma migrate dev`, it RESETS gifsy_dev).
-- DDL generated by `prisma migrate diff --from-schema <HEAD baseline> --to-schema
-- prisma/schema.prisma --script` (2026-06-17), then wrapped with the gifsy_dev
-- guard (BEGIN/DO/COMMIT, hand-added per project convention). Independently
-- audited 2026-06-17 (PASS); reviewed in
-- docs/plans/reconcile/P4-programs-targets-enrollment.md §3.
--
-- Additive only — no drops, no NOT-NULL-without-default on existing tables:
--   • scheme_enrollments: +enrollmentMode (default 'SELF') +formValues (nullable)
--   • NEW scheme_enrollment_forms (1:1 Scheme)   [Stream E — enrollment]
--   • NEW kpi_defs (per-tenant parameters)        [Stream T — targets]
--   • NEW target_upload_batches + outlet_targets  [Stream T — targets]
-- The World-A SchemeTarget DROP is a SEPARATE destructive step sequenced WITH the
-- 4.1 code change (its reads live in api/src/schemes) — NOT in this file.

BEGIN;
DO $$ BEGIN
  IF current_database() <> 'gifsy_dev' THEN
    RAISE EXCEPTION 'Refusing to run: expected gifsy_dev, got %', current_database();
  END IF;
END $$;

-- AlterTable
ALTER TABLE "scheme_enrollments" ADD COLUMN     "enrollmentMode" TEXT NOT NULL DEFAULT 'SELF',
ADD COLUMN     "formValues" JSONB;

-- CreateTable
CREATE TABLE "scheme_enrollment_forms" (
    "id" TEXT NOT NULL,
    "schemeId" TEXT NOT NULL,
    "campaignType" TEXT NOT NULL DEFAULT 'LOYALTY_ONLY',
    "formSchema" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "scheme_enrollment_forms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kpi_defs" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "unit" TEXT NOT NULL DEFAULT '',
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "hasNameOverride" BOOLEAN NOT NULL DEFAULT false,
    "nameOverrideLabel" TEXT,
    -- "order" is a SQL reserved word; quoted deliberately (do not unquote).
    "order" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kpi_defs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "target_upload_batches" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "uploadedById" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "totalRows" INTEGER NOT NULL DEFAULT 0,
    "acceptedCount" INTEGER NOT NULL DEFAULT 0,
    "rejectedCount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'COMPLETED',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "target_upload_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outlet_targets" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "outletCode" TEXT NOT NULL,
    "outletName" TEXT NOT NULL,
    "outletType" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "targetValues" JSONB NOT NULL,
    "batchId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "outlet_targets_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "scheme_enrollment_forms_schemeId_key" ON "scheme_enrollment_forms"("schemeId");

-- CreateIndex
CREATE INDEX "kpi_defs_clientId_idx" ON "kpi_defs"("clientId");

-- CreateIndex
CREATE UNIQUE INDEX "kpi_defs_clientId_code_key" ON "kpi_defs"("clientId", "code");

-- CreateIndex
CREATE INDEX "target_upload_batches_clientId_idx" ON "target_upload_batches"("clientId");

-- CreateIndex
CREATE INDEX "target_upload_batches_month_idx" ON "target_upload_batches"("month");

-- CreateIndex
CREATE INDEX "target_upload_batches_uploadedById_idx" ON "target_upload_batches"("uploadedById");

-- CreateIndex
CREATE INDEX "outlet_targets_clientId_idx" ON "outlet_targets"("clientId");

-- CreateIndex
CREATE INDEX "outlet_targets_month_idx" ON "outlet_targets"("month");

-- CreateIndex
CREATE INDEX "outlet_targets_outletCode_idx" ON "outlet_targets"("outletCode");

-- CreateIndex
CREATE INDEX "outlet_targets_batchId_idx" ON "outlet_targets"("batchId");

-- CreateIndex
CREATE UNIQUE INDEX "outlet_targets_clientId_outletCode_month_key" ON "outlet_targets"("clientId", "outletCode", "month");

-- AddForeignKey
ALTER TABLE "scheme_enrollment_forms" ADD CONSTRAINT "scheme_enrollment_forms_schemeId_fkey" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "outlet_targets" ADD CONSTRAINT "outlet_targets_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "target_upload_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
