/**
 * Credits & Payouts — UTR Upload Parser (pure / injectable)
 *
 * parseUtrUpload accepts all batch data as parameters — no localStorage.
 * The API route loads data from DB before calling this function.
 *
 * UTR validations:
 *  - Format: 8–22 alphanumeric characters (covers NEFT/IMPS/RTGS/UPI)
 *  - Duplicate UTR detection via injected knownUtrs set
 *  - Outlet ID must exist in the injected batchRows
 *  - Already-PAID rows are skipped (idempotency)
 *
 * Success/Failure column accepts: "Success", "1", "Y", "Yes", "TRUE" → success
 * Anything else → failure
 *
 * Expected sheet format (generated by generatePayoutFileBuffer):
 *   Row 0: title (skipped)
 *   Row 1: headers
 *   Row 2+: data
 */

import * as XLSX from 'xlsx';
import type { UtrParseResult, UtrUploadRow } from '@/types';

// ─── UTR format validator ─────────────────────────────────────────────────────

const UTR_RE = /^[A-Z0-9]{8,22}$/i;

export function isValidUtr(utr: string): boolean {
  return UTR_RE.test(utr.trim());
}

// ─── Success/Failure normaliser ───────────────────────────────────────────────

function parseSuccess(raw: string): boolean {
  const v = String(raw).trim().toUpperCase();
  return ['SUCCESS', '1', 'Y', 'YES', 'TRUE'].includes(v);
}

// ─── Injectable batch row type ────────────────────────────────────────────────

export interface UtrBatchRow {
  outletId:  string;
  utrStatus: 'PENDING' | 'PAID' | 'FAILED';
  utr?:      string;
}

export interface ParseUtrUploadOpts {
  downloadCode: string;       // Expected "Batch ID" in the file (the payout download code)
  batchRows:    UtrBatchRow[]; // Pre-loaded from DB (CreditPayoutEntry rows for this download)
  knownUtrs:    Set<string>;   // Already-used UTRs across all downloads, for dup detection
}

// ─── Parser ───────────────────────────────────────────────────────────────────

export function parseUtrUpload(
  buffer: ArrayBuffer,
  opts:   ParseUtrUploadOpts,
): UtrParseResult {
  const { downloadCode, batchRows, knownUtrs } = opts;

  if (!batchRows.length) {
    return {
      headerError: `No payout entries found for download "${downloadCode}".`,
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  // Parse workbook
  let wb: XLSX.WorkBook;
  try {
    wb = XLSX.read(buffer, { type: 'array' });
  } catch {
    return {
      headerError: 'Could not read file. Please upload a valid .xlsx file.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  const sheetName = wb.SheetNames[0];
  const ws        = wb.Sheets[sheetName];
  const allRows   = XLSX.utils.sheet_to_json<(string | number)[]>(ws, { header: 1, defval: '' }) as (string | number)[][];

  if (allRows.length < 2) {
    return {
      headerError: 'File has no header row.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  // Row 1 = headers (row 0 = title)
  const headers     = allRows[1].map((h) => String(h).trim());
  const outletIdIdx = headers.indexOf('Outlet ID');
  const batchIdIdx  = headers.indexOf('Batch ID');
  const utrIdx      = headers.indexOf('UTR');
  const successIdx  = headers.indexOf('Success/Failure');
  const remarksIdx  = headers.indexOf('Remarks');

  if (outletIdIdx === -1 || utrIdx === -1) {
    return {
      headerError: 'Missing "Outlet ID" or "UTR" column. Please use the official payout file.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  const batchRowMap = new Map(batchRows.map((r) => [r.outletId, r]));
  const seenUtrs = new Set<string>();
  const rows: UtrUploadRow[] = [];
  let paidCount = 0; let failedCount = 0;

  for (let rIdx = 2; rIdx < allRows.length; rIdx++) {
    const row      = allRows[rIdx];
    const outletId = String(row[outletIdIdx] ?? '').trim();
    if (!outletId) continue;

    const fileBatchId = batchIdIdx !== -1 ? String(row[batchIdIdx] ?? '').trim() : '';
    const utrRaw      = String(row[utrIdx]      ?? '').trim();
    const successRaw  = successIdx  !== -1 ? String(row[successIdx]  ?? '').trim() : '';
    const remarksRaw  = remarksIdx  !== -1 ? String(row[remarksIdx]  ?? '').trim() : '';

    const batchRow  = batchRowMap.get(outletId);
    const errors: string[] = [];

    // Already paid — skip (idempotency)
    if (batchRow?.utrStatus === 'PAID') {
      rows.push({
        rowNum: rIdx + 1, outletId,
        batchId: fileBatchId || downloadCode,
        utr: utrRaw, success: true, remarks: remarksRaw,
        status: 'SKIP', errors: [],
      });
      continue;
    }

    // Outlet not in batch
    if (!batchRow) {
      errors.push(`Outlet ID "${outletId}" not found in batch "${downloadCode}".`);
    }

    // Batch ID mismatch
    if (fileBatchId && fileBatchId !== downloadCode) {
      errors.push(`Batch ID "${fileBatchId}" does not match expected "${downloadCode}".`);
    }

    const success = parseSuccess(successRaw);

    if (success) {
      if (!utrRaw) {
        errors.push('UTR is required for successful payments.');
      } else {
        if (!isValidUtr(utrRaw)) {
          errors.push(`UTR "${utrRaw}" is not valid (must be 8–22 alphanumeric characters).`);
        }
        const normUtr = utrRaw.toUpperCase();
        if (knownUtrs.has(normUtr) && !(batchRow?.utr?.toUpperCase() === normUtr)) {
          errors.push(`UTR "${utrRaw}" has already been used in a previous batch.`);
        }
        if (seenUtrs.has(normUtr)) {
          errors.push(`UTR "${utrRaw}" appears more than once in this upload.`);
        } else if (errors.length === 0) {
          seenUtrs.add(normUtr);
        }
      }
    }

    const status: 'OK' | 'ERROR' = errors.length > 0 ? 'ERROR' : 'OK';
    if (status === 'OK') {
      if (success) paidCount++; else failedCount++;
    }

    rows.push({
      rowNum:  rIdx + 1,
      outletId,
      batchId: fileBatchId || downloadCode,
      utr:     utrRaw,
      success,
      remarks: remarksRaw,
      status,
      errors,
    });
  }

  const okCount    = rows.filter((r) => r.status === 'OK').length;
  const skipCount  = rows.filter((r) => r.status === 'SKIP').length;
  const errCount   = rows.filter((r) => r.status === 'ERROR').length;

  return {
    headerError: null,
    rows,
    hasErrors:   errCount > 0,
    canProceed:  !!(okCount > 0 && errCount === 0),
    summary: {
      total:       okCount + errCount,
      ok:          okCount,
      skipped:     skipCount,
      errors:      errCount,
      paidCount,
      failedCount,
    },
  };
}
