/**
 * Credits & Payouts — Upload Parser
 *
 * Parses an Excel file uploaded by the client admin, validates each row,
 * and returns a CreditParseResult.
 *
 * Validation rules per outlet+field cell:
 *  1. Outlet ID must exist in eligible outlets
 *  2. Outlet must be active
 *  3. Zero or blank value → SKIP (not an error)
 *  4. Negative value → ERROR
 *  5. More than 1 decimal place → ERROR
 *  6. Amount exceeds safety cap → ERROR
 *  7. Duplicate outlet+field in the same upload → ERROR on second occurrence
 *  8. Field configured as NA for this outlet type → SKIP
 *
 * Expected sheet format (generated by generateCreditTemplate):
 *   Row 0: title (skipped)
 *   Row 1: headers  — Outlet ID | Outlet Name | Field1 | ... | FieldN | Field1 Narration | ...
 *   Row 2+: data
 */

import * as XLSX from 'xlsx';
import type { CreditField, CreditParseResult, CreditUploadRow } from '@/types';
import type { TemplateOutlet } from './credits-payouts-template';

export interface ParseCreditUploadOpts {
  fields:      CreditField[];
  outlets:     TemplateOutlet[];
  month:       string;         // 'YYYY-MM'
  safetyCapPoints: number;
  safetyCapInr:    number;
}

// ─── Decimal validation ───────────────────────────────────────────────────────

/** Returns true if the number has more than 1 decimal place. */
function moreThanOneDecimal(n: number): boolean {
  const str = n.toString();
  const dotIndex = str.indexOf('.');
  if (dotIndex === -1) return false;
  return str.length - dotIndex - 1 > 1;
}

// ─── Parser ───────────────────────────────────────────────────────────────────

export function parseCreditUpload(
  buffer:  ArrayBuffer,
  opts:    ParseCreditUploadOpts,
): CreditParseResult {
  const { fields, outlets, safetyCapPoints, safetyCapInr } = opts;

  // Build outlet lookup
  const outletMap = new Map<string, TemplateOutlet>();
  for (const o of outlets) outletMap.set(o.id, o);

  // Active fields only, in order
  const activeFields = fields.filter((f) => f.isActive);

  // Parse workbook
  let wb: XLSX.WorkBook;
  try {
    wb = XLSX.read(buffer, { type: 'array' });
  } catch {
    return {
      headerError: 'Could not read the uploaded file. Please upload a valid .xlsx file.',
      rows:        [],
      hasErrors:   false,
      canProceed:  false,
      summary:     { total: 0, ok: 0, skipped: 0, errors: 0, totalPoints: 0, totalPayoutInr: 0 },
    };
  }

  const sheetName = wb.SheetNames[0];
  if (!sheetName) {
    return {
      headerError: 'The uploaded file has no sheets.',
      rows:        [],
      hasErrors:   false,
      canProceed:  false,
      summary:     { total: 0, ok: 0, skipped: 0, errors: 0, totalPoints: 0, totalPayoutInr: 0 },
    };
  }

  const ws = wb.Sheets[sheetName];

  // Read all rows as arrays (row 0 = title, row 1 = headers, row 2+ = data)
  const allRows = XLSX.utils.sheet_to_json<(string | number)[]>(ws, {
    header: 1,
    defval: '',
  }) as (string | number)[][];

  if (allRows.length < 2) {
    return {
      headerError: 'The file has no header row.',
      rows:        [],
      hasErrors:   false,
      canProceed:  false,
      summary:     { total: 0, ok: 0, skipped: 0, errors: 0, totalPoints: 0, totalPayoutInr: 0 },
    };
  }

  // Row index 1 is the header row (row index 0 is title)
  const headerRow = allRows[1].map((h) => String(h).trim());
  const outletIdIdx   = headerRow.indexOf('Outlet ID');
  const outletNameIdx = headerRow.indexOf('Outlet Name');

  if (outletIdIdx === -1) {
    return {
      headerError: 'Missing "Outlet ID" column. Please use the official template.',
      rows:        [],
      hasErrors:   false,
      canProceed:  false,
      summary:     { total: 0, ok: 0, skipped: 0, errors: 0, totalPoints: 0, totalPayoutInr: 0 },
    };
  }

  // Map field name → column index for both values and narrations
  const fieldValueIdx     = new Map<string, number>();
  const fieldNarrationIdx = new Map<string, number>();
  for (const f of activeFields) {
    const vi = headerRow.indexOf(f.name);
    const ni = headerRow.indexOf(`${f.name} Narration`);
    if (vi !== -1) fieldValueIdx.set(f.id, vi);
    if (ni !== -1) fieldNarrationIdx.set(f.id, ni);
  }

  // Track duplicates: "outletId|fieldId"
  const seen = new Set<string>();

  const rows: CreditUploadRow[] = [];
  let totalPoints    = 0;
  let totalPayoutInr = 0;

  // Data rows start at index 2
  for (let rIdx = 2; rIdx < allRows.length; rIdx++) {
    const row = allRows[rIdx];
    const outletId   = String(row[outletIdIdx] ?? '').trim();
    const outletName = outletNameIdx !== -1 ? String(row[outletNameIdx] ?? '').trim() : '';

    if (!outletId) continue;  // blank row

    const outlet = outletMap.get(outletId);

    // Process each active field as a separate result row
    for (const field of activeFields) {
      const vi = fieldValueIdx.get(field.id);
      if (vi === undefined) continue;  // column not in file

      const rawVal   = row[vi] ?? '';
      const rawNarr  = fieldNarrationIdx.has(field.id)
        ? String(row[fieldNarrationIdx.get(field.id)!] ?? '').trim()
        : '';

      const strVal = String(rawVal).trim();

      // SKIP: blank or zero (check before outlet validation so blanks don't generate errors)
      if (strVal === '' || strVal === '0') {
        rows.push({
          rowNum:    rIdx + 1,
          outletId,
          outletName: outletName || (outlet?.name ?? outletId),
          fieldId:   field.id,
          fieldName: field.name,
          amount:    0,
          narration: rawNarr,
          awardType: 'POINTS',
          status:    'SKIP',
          errors:    [],
        });
        continue;
      }

      const errors: string[] = [];

      // Unknown outlet — must be validated before NA check
      if (!outlet) {
        errors.push(`Outlet ID "${outletId}" not found in the active outlet master.`);
      }

      // Determine award type for this outlet type (only when outlet is known)
      const awardType: 'POINTS' | 'PAYOUT' | 'NA' =
        outlet ? (field.outletTypeAwards[outlet.type] ?? 'NA') : 'POINTS';

      // SKIP: NA field for this outlet type (only when outlet is known and no other error)
      if (outlet && awardType === 'NA') {
        rows.push({
          rowNum:    rIdx + 1,
          outletId,
          outletName: outlet.name,
          fieldId:   field.id,
          fieldName: field.name,
          amount:    0,
          narration: rawNarr,
          awardType: 'POINTS',
          status:    'SKIP',
          errors:    [],
        });
        continue;
      }

      // Parse numeric value
      const numVal = Number(strVal.replace(/,/g, ''));

      if (isNaN(numVal)) {
        errors.push(`Value "${strVal}" is not a valid number.`);
      } else {
        // Negative
        if (numVal < 0) {
          errors.push(`Amount cannot be negative (got ${numVal}).`);
        }
        // More than 1 decimal place
        if (moreThanOneDecimal(numVal)) {
          errors.push(`Amount "${strVal}" has more than 1 decimal place. Maximum 1 decimal allowed.`);
        }
        // Safety cap
        const cap = awardType === 'POINTS' ? safetyCapPoints : safetyCapInr;
        if (numVal > cap) {
          errors.push(`Amount ${numVal} exceeds the safety cap of ${cap} for ${awardType === 'POINTS' ? 'points' : '₹'}.`);
        }
      }

      // Duplicate check
      const dedupKey = `${outletId}|${field.id}`;
      if (seen.has(dedupKey)) {
        errors.push(`Duplicate entry: Outlet "${outletId}" + Field "${field.name}" appears more than once in this upload.`);
      } else if (errors.length === 0) {
        seen.add(dedupKey);
      }

      const amount = isNaN(numVal) ? 0 : numVal;
      const status: 'OK' | 'ERROR' = errors.length > 0 ? 'ERROR' : 'OK';
      // awardType at this point is always POINTS or PAYOUT (NA was handled above)
      const resolvedAwardType: 'POINTS' | 'PAYOUT' = awardType === 'PAYOUT' ? 'PAYOUT' : 'POINTS';

      if (status === 'OK') {
        if (resolvedAwardType === 'POINTS') totalPoints    += amount;
        else                               totalPayoutInr += amount;
      }

      rows.push({
        rowNum:    rIdx + 1,
        outletId,
        outletName: outletName || (outlet?.name ?? outletId),
        fieldId:   field.id,
        fieldName: field.name,
        amount,
        narration: rawNarr,
        awardType: resolvedAwardType,
        status,
        errors,
      });
    }
  }

  const okCount      = rows.filter((r) => r.status === 'OK').length;
  const skippedCount = rows.filter((r) => r.status === 'SKIP').length;
  const errorCount   = rows.filter((r) => r.status === 'ERROR').length;
  const hasErrors    = errorCount > 0;

  return {
    headerError:   null,
    rows,
    hasErrors,
    canProceed:    !hasErrors && okCount > 0,
    summary: {
      total:          okCount + errorCount,
      ok:             okCount,
      skipped:        skippedCount,
      errors:         errorCount,
      totalPoints,
      totalPayoutInr,
    },
  };
}
