/**
 * Credits & Payouts — UTR Upload Parser & Applier
 *
 * Gifsy uploads the payout file back with UTR numbers filled in.
 * This module parses and validates the uploaded file, then updates
 * payout batch rows + payout entries accordingly.
 *
 * UTR validations:
 *  - Format: 8–22 alphanumeric characters (covers NEFT/IMPS/RTGS/UPI)
 *  - Duplicate UTR detection across ALL batches in storage
 *  - Outlet ID must exist in the referenced payout batch
 *  - Already-PAID rows are skipped (idempotency)
 *
 * Amount reconciliation:
 *  - Warns if the sum of amounts in the UTR file differs from batch total
 *  - Does NOT block processing (just a warning)
 *
 * Success/Failure column accepts: "Success", "1", "Y", "Yes", "TRUE" → success
 * Anything else → failure
 *
 * Expected sheet format (generated by generatePayoutFileBuffer):
 *   Row 0: title (skipped)
 *   Row 1: headers
 *   Row 2+: data
 */

import * as XLSX from 'xlsx';
import type { PayoutBatch, UtrParseResult, UtrUploadRow } from '@/types';
import {
  getPayoutBatch,
  savePayoutBatch,
  updatePayoutEntryStatus,
  getAllPayoutBatches,
} from './credits-payouts-payout-store';

// ─── UTR format validator ─────────────────────────────────────────────────────

const UTR_RE = /^[A-Z0-9]{8,22}$/i;

export function isValidUtr(utr: string): boolean {
  return UTR_RE.test(utr.trim());
}

// ─── Success/Failure normaliser ───────────────────────────────────────────────

function parseSuccess(raw: string): boolean {
  const v = String(raw).trim().toUpperCase();
  return ['SUCCESS', '1', 'Y', 'YES', 'TRUE'].includes(v);
}

// ─── Collect all known UTRs (for duplicate detection) ────────────────────────

function collectKnownUtrs(): Set<string> {
  const known = new Set<string>();
  for (const batch of getAllPayoutBatches()) {
    for (const row of batch.rows) {
      if (row.utr) known.add(row.utr.trim().toUpperCase());
    }
  }
  return known;
}

// ─── Parser ───────────────────────────────────────────────────────────────────

export interface ParseUtrUploadOpts {
  batchId: string;   // which PayoutBatch this file belongs to
}

export function parseUtrUpload(
  buffer: ArrayBuffer,
  opts:   ParseUtrUploadOpts,
): UtrParseResult {
  const { batchId } = opts;

  // Load the batch
  const batch = getPayoutBatch(batchId);
  if (!batch) {
    return {
      headerError: `Payout batch "${batchId}" not found. Please use the file downloaded from the payout screen.`,
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  // Parse workbook
  let wb: XLSX.WorkBook;
  try {
    wb = XLSX.read(buffer, { type: 'array' });
  } catch {
    return {
      headerError: 'Could not read file. Please upload a valid .xlsx file.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  const sheetName = wb.SheetNames[0];
  const ws        = wb.Sheets[sheetName];
  const allRows   = XLSX.utils.sheet_to_json<(string | number)[]>(ws, { header: 1, defval: '' }) as (string | number)[][];

  if (allRows.length < 2) {
    return {
      headerError: 'File has no header row.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  // Row 1 = headers (row 0 = title)
  const headers     = allRows[1].map((h) => String(h).trim());
  const outletIdIdx = headers.indexOf('Outlet ID');
  const batchIdIdx  = headers.indexOf('Batch ID');
  const utrIdx      = headers.indexOf('UTR');
  const successIdx  = headers.indexOf('Success/Failure');
  const remarksIdx  = headers.indexOf('Remarks');

  if (outletIdIdx === -1 || utrIdx === -1) {
    return {
      headerError: 'Missing "Outlet ID" or "UTR" column. Please use the official payout file.',
      rows: [], hasErrors: false, canProceed: false,
      summary: { total: 0, ok: 0, skipped: 0, errors: 0, paidCount: 0, failedCount: 0 },
    };
  }

  // Build outlet lookup from batch rows
  const batchRowMap = new Map(batch.rows.map((r) => [r.outletId, r]));

  // Collect all known UTRs (for dup detection)
  const knownUtrs = collectKnownUtrs();

  const rows: UtrUploadRow[] = [];
  const seenUtrs = new Set<string>();
  let paidCount = 0; let failedCount = 0;

  for (let rIdx = 2; rIdx < allRows.length; rIdx++) {
    const row      = allRows[rIdx];
    const outletId = String(row[outletIdIdx] ?? '').trim();
    if (!outletId) continue;

    const fileBatchId = batchIdIdx !== -1 ? String(row[batchIdIdx] ?? '').trim() : '';
    const utrRaw      = String(row[utrIdx]      ?? '').trim();
    const successRaw  = successIdx  !== -1 ? String(row[successIdx]  ?? '').trim() : '';
    const remarksRaw  = remarksIdx  !== -1 ? String(row[remarksIdx]  ?? '').trim() : '';

    const batchRow  = batchRowMap.get(outletId);
    const errors: string[] = [];

    // Already paid — skip (idempotency)
    if (batchRow?.utrStatus === 'PAID') {
      rows.push({
        rowNum: rIdx + 1, outletId,
        batchId: fileBatchId || batchId,
        utr: utrRaw, success: true, remarks: remarksRaw,
        status: 'SKIP', errors: [],
      });
      continue;
    }

    // Outlet not in batch
    if (!batchRow) {
      errors.push(`Outlet ID "${outletId}" not found in batch "${batchId}".`);
    }

    // Batch ID mismatch
    if (fileBatchId && fileBatchId !== batchId) {
      errors.push(`Batch ID "${fileBatchId}" does not match expected "${batchId}".`);
    }

    const success = parseSuccess(successRaw);

    // UTR required for success rows
    if (success) {
      if (!utrRaw) {
        errors.push('UTR is required for successful payments.');
      } else {
        // Format check
        if (!isValidUtr(utrRaw)) {
          errors.push(`UTR "${utrRaw}" is not valid (must be 8–22 alphanumeric characters).`);
        }
        // Duplicate check (across all batches)
        const normUtr = utrRaw.toUpperCase();
        if (knownUtrs.has(normUtr) && !(batchRow?.utr?.toUpperCase() === normUtr)) {
          errors.push(`UTR "${utrRaw}" has already been used in a previous batch.`);
        }
        // Within-file duplicate
        if (seenUtrs.has(normUtr)) {
          errors.push(`UTR "${utrRaw}" appears more than once in this upload.`);
        } else if (errors.length === 0) {
          seenUtrs.add(normUtr);
        }
      }
    }

    const status: 'OK' | 'ERROR' = errors.length > 0 ? 'ERROR' : 'OK';
    if (status === 'OK') {
      if (success) paidCount++; else failedCount++;
    }

    rows.push({
      rowNum:  rIdx + 1,
      outletId,
      batchId: fileBatchId || batchId,
      utr:     utrRaw,
      success,
      remarks: remarksRaw,
      status,
      errors,
    });
  }

  const okCount    = rows.filter((r) => r.status === 'OK').length;
  const skipCount  = rows.filter((r) => r.status === 'SKIP').length;
  const errCount   = rows.filter((r) => r.status === 'ERROR').length;

  return {
    headerError: null,
    rows,
    hasErrors:   errCount > 0,
    canProceed:  !!(okCount > 0 && errCount === 0),
    summary: {
      total:       okCount + errCount,
      ok:          okCount,
      skipped:     skipCount,
      errors:      errCount,
      paidCount,
      failedCount,
    },
  };
}

// ─── Apply UTR result to batch + entries ──────────────────────────────────────

export interface ApplyUtrResult {
  paidCount:   number;
  failedCount: number;
  skippedCount: number;
}

export function applyUtrResult(
  parseResult: UtrParseResult,
  batchId:     string,
): ApplyUtrResult {
  const batch = getPayoutBatch(batchId);
  if (!batch || !parseResult.canProceed) {
    return { paidCount: 0, failedCount: 0, skippedCount: 0 };
  }

  let paidCount = 0; let failedCount = 0; let skippedCount = 0;

  const updatedBatch = { ...batch, rows: [...batch.rows] };

  for (const row of parseResult.rows) {
    if (row.status === 'SKIP') { skippedCount++; continue; }
    if (row.status !== 'OK')   continue;

    // Update batch row
    const batchRowIdx = updatedBatch.rows.findIndex((r) => r.outletId === row.outletId);
    if (batchRowIdx !== -1) {
      const batchRow = updatedBatch.rows[batchRowIdx];
      updatedBatch.rows[batchRowIdx] = {
        ...batchRow,
        utrStatus:     row.success ? 'PAID' : 'FAILED',
        utr:           row.success ? row.utr : undefined,
        paidAt:        row.success ? new Date().toISOString() : undefined,
        failureReason: row.success ? undefined : row.remarks || 'Bank transfer failed',
      };
    }

    // Update individual payout entries
    const batchRow = batch.rows.find((r) => r.outletId === row.outletId);
    if (batchRow) {
      for (const entryId of batchRow.entryIds) {
        updatePayoutEntryStatus(
          entryId,
          row.success ? 'PAID' : 'FAILED',
          row.success ? row.utr : undefined,
        );
      }
    }

    if (row.success) paidCount++; else failedCount++;
  }

  // Update batch status
  const allRows = updatedBatch.rows;
  const pendingRows = allRows.filter((r) => r.utrStatus === 'PENDING');
  const paidRows    = allRows.filter((r) => r.utrStatus === 'PAID');
  const failedRows  = allRows.filter((r) => r.utrStatus === 'FAILED');

  updatedBatch.status =
    pendingRows.length === 0 && failedRows.length === 0 ? 'PAID'
    : pendingRows.length === 0                          ? 'FAILED'
    : paidRows.length > 0                              ? 'PARTIALLY_PAID'
    :                                                    'OPEN';

  savePayoutBatch(updatedBatch);

  return { paidCount, failedCount, skippedCount };
}
