/**
 * Visibility Invoice Module — Core types, calculation helpers, mock data.
 *
 * Self-billing arrangement: invoices are generated by Tech Gifsy Solutions
 * Limited on behalf of the retailer (service provider) for marketing
 * visibility services rendered.
 *
 * TAX HANDLING (INTERNAL ONLY — never surface in UI):
 *  - TDS is computed internally for compliance; retailer sees gross only.
 *  - GST is shown on invoice only for REGULAR GST-registered retailers.
 *  - Tech Gifsy is registered in West Bengal:
 *      intra-state (WB retailer) → CGST 9% + SGST 9%
 *      inter-state               → IGST 18%
 */

// ─────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────

export type EntityType =
  | 'INDIVIDUAL'
  | 'HUF'
  | 'COMPANY'
  | 'FIRM'
  | 'LLP'
  | 'OTHERS';

export type GSTRegistrationType =
  | 'REGULAR'
  | 'UNREGISTERED'
  | 'COMPOSITE';

export type VisibilityInvoiceStatus = 'GENERATED' | 'PAID';

// ─────────────────────────────────────────────
// Core interface
// ─────────────────────────────────────────────

export interface VisibilityInvoice {
  /** Primary key */
  id: string;

  /** Invoice number — format: TGSL-VIS-[OUTLET_CODE]-[YYYYMM]-[SEQ] */
  invoiceNumber: string;

  /** Whether the retailer has edited the invoice number */
  invoiceNumberEdited: boolean;

  status: VisibilityInvoiceStatus;

  // ── Period ──
  /** e.g. "2025-01" */
  period: string;
  /** Human-readable e.g. "January 2025" */
  periodLabel: string;

  // ── Outlet / Retailer snapshot (frozen at generation time) ──
  outletId: string;
  outletCode: string;
  outletName: string;
  firmName: string;
  partnerName: string;
  mobile: string;

  /** State in which the retailer operates */
  retailerState: string;

  // ── KYC snapshot ──
  panNumber: string | null;
  gstNumber: string | null;
  entityType: EntityType;
  gstRegistrationType: GSTRegistrationType;

  bankName: string;
  accountNumber: string;
  ifscCode: string;

  // ── Amounts ──
  /** Base payout amount from the uploaded Excel (pre-GST) */
  baseAmount: number;

  /** GST applicable only for REGULAR retailers */
  gstApplicable: boolean;
  /** 'CGST_SGST' for WB intra-state, 'IGST' for inter-state, null if no GST */
  gstType: 'CGST_SGST' | 'IGST' | null;
  cgst: number;
  sgst: number;
  igst: number;
  totalGST: number;
  /** baseAmount + totalGST */
  totalInvoiceAmount: number;

  // ── TDS (internal — never shown in UI) ──
  tdsRate: number;   // 0.01, 0.02, or 0.20
  tdsAmount: number;
  /** Amount actually disbursed to retailer = baseAmount − tdsAmount */
  netDisbursed: number;

  // ── Meta ──
  generatedAt: string;   // ISO date string
  paidAt: string | null; // ISO date string
  uploadBatchId: string;

  /** SAC code for visibility marketing services */
  sacCode: '998361';

  /** Invoice description — always this fixed string */
  description: string; // "Marketing visibility services — [Month Year]"
}

// ─────────────────────────────────────────────
// Calculation helpers
// ─────────────────────────────────────────────

const TECH_GIFSY_STATE = 'West Bengal';

/**
 * Compute TDS details.
 * Rates (internal, never shown):
 *   INDIVIDUAL | HUF → 1%
 *   No PAN           → 20%
 *   Others           → 2%
 */
export function computeTDS(
  baseAmount: number,
  entityType: EntityType,
  pan: string | null,
): { tdsRate: number; tdsAmount: number; netDisbursed: number } {
  let tdsRate: number;

  if (!pan) {
    tdsRate = 0.20;
  } else if (entityType === 'INDIVIDUAL' || entityType === 'HUF') {
    tdsRate = 0.01;
  } else {
    tdsRate = 0.02;
  }

  const tdsAmount = Math.round(baseAmount * tdsRate * 100) / 100;
  const netDisbursed = Math.round((baseAmount - tdsAmount) * 100) / 100;

  return { tdsRate, tdsAmount, netDisbursed };
}

/**
 * Compute GST details.
 * GST is applied ONLY for REGULAR GST-registered retailers.
 * Rate: 18% (SAC 998361)
 *   Intra-state (retailer in WB) → CGST 9% + SGST 9%
 *   Inter-state                  → IGST 18%
 */
export function computeGST(
  baseAmount: number,
  gstRegistrationType: GSTRegistrationType,
  retailerState: string,
): {
  gstApplicable: boolean;
  gstType: 'CGST_SGST' | 'IGST' | null;
  cgst: number;
  sgst: number;
  igst: number;
  totalGST: number;
  totalInvoiceAmount: number;
} {
  if (gstRegistrationType !== 'REGULAR') {
    return {
      gstApplicable: false,
      gstType: null,
      cgst: 0,
      sgst: 0,
      igst: 0,
      totalGST: 0,
      totalInvoiceAmount: baseAmount,
    };
  }

  const intraState =
    retailerState.trim().toLowerCase() === TECH_GIFSY_STATE.toLowerCase();

  const r = (n: number) => Math.round(n * 100) / 100;

  if (intraState) {
    const cgst = r(baseAmount * 0.09);
    const sgst = r(baseAmount * 0.09);
    const totalGST = r(cgst + sgst);
    return {
      gstApplicable: true,
      gstType: 'CGST_SGST',
      cgst,
      sgst,
      igst: 0,
      totalGST,
      totalInvoiceAmount: r(baseAmount + totalGST),
    };
  } else {
    const igst = r(baseAmount * 0.18);
    return {
      gstApplicable: true,
      gstType: 'IGST',
      cgst: 0,
      sgst: 0,
      igst,
      totalGST: igst,
      totalInvoiceAmount: r(baseAmount + igst),
    };
  }
}

/**
 * Format a period string "YYYY-MM" → human label "Month YYYY"
 */
export function formatPeriodLabel(period: string): string {
  const [year, month] = period.split('-');
  const date = new Date(Number(year), Number(month) - 1, 1);
  return date.toLocaleString('en-IN', { month: 'long', year: 'numeric' });
}

/**
 * Generate invoice number.
 * Format: TGSL-VIS-[OUTLET_CODE]-[YYYYMM]-[SEQ]
 * seq is zero-padded to 3 digits.
 */
export function generateInvoiceNumber(
  outletCode: string,
  period: string,          // "YYYY-MM"
  seq: number,
): string {
  const yyyymm = period.replace('-', '');
  const seqStr = String(seq).padStart(3, '0');
  return `TGSL-VIS-${outletCode.toUpperCase()}-${yyyymm}-${seqStr}`;
}

/**
 * Build the fixed invoice description for a period.
 */
export function buildInvoiceDescription(periodLabel: string): string {
  return `Marketing visibility services — ${periodLabel}`;
}

// ─────────────────────────────────────────────
// Mock data
// ─────────────────────────────────────────────

/**
 * Demo invoices covering the four main cases:
 *   1. Regular GST, West Bengal (intra-state → CGST+SGST), individual retailer
 *   2. Regular GST, Maharashtra (inter-state → IGST), company retailer
 *   3. Unregistered GST (no GST on invoice), individual retailer
 *   4. No PAN number (20% TDS internally), firm retailer
 */
export const MOCK_VISIBILITY_INVOICES: VisibilityInvoice[] = (() => {
  function build(
    id: string,
    seq: number,
    outletId: string,
    outletCode: string,
    outletName: string,
    firmName: string,
    partnerName: string,
    mobile: string,
    retailerState: string,
    pan: string | null,
    gstNumber: string | null,
    entityType: EntityType,
    gstRegType: GSTRegistrationType,
    bankName: string,
    accountNumber: string,
    ifscCode: string,
    baseAmount: number,
    period: string,
    status: VisibilityInvoiceStatus,
    generatedAt: string,
    paidAt: string | null,
  ): VisibilityInvoice {
    const periodLabel = formatPeriodLabel(period);
    const invoiceNumber = generateInvoiceNumber(outletCode, period, seq);
    const tds = computeTDS(baseAmount, entityType, pan);
    const gst = computeGST(baseAmount, gstRegType, retailerState);

    return {
      id,
      invoiceNumber,
      invoiceNumberEdited: false,
      status,
      period,
      periodLabel,
      outletId,
      outletCode,
      outletName,
      firmName,
      partnerName,
      mobile,
      retailerState,
      panNumber: pan,
      gstNumber,
      entityType,
      gstRegistrationType: gstRegType,
      bankName,
      accountNumber,
      ifscCode,
      baseAmount,
      ...gst,
      ...tds,
      sacCode: '998361',
      description: buildInvoiceDescription(periodLabel),
      generatedAt,
      paidAt,
      uploadBatchId: `BATCH-${period.replace('-', '')}-001`,
    };
  }

  return [
    // 1. Regular GST, West Bengal — intra-state CGST+SGST, Individual
    build(
      'inv-001', 1,
      'o2', 'O2', 'Sharma Kirana Store', 'Sharma Enterprises', 'Rajesh Sharma',
      '9876543210',
      'West Bengal',
      'ABCPS1234D', '19ABCPS1234D1Z5',
      'INDIVIDUAL', 'REGULAR',
      'State Bank of India', '1234567890', 'SBIN0001234',
      5000, '2025-01', 'PAID', '2025-02-01T10:00:00Z', '2025-02-15T14:30:00Z',
    ),

    // 2. Regular GST, Maharashtra — inter-state IGST, Company
    build(
      'inv-002', 2,
      'o4', 'O4', 'Metro General Store', 'Metro Retail Pvt Ltd', 'Suresh Mehta',
      '9876500001',
      'Maharashtra',
      'AABCM1234F', '27AABCM1234F1Z3',
      'COMPANY', 'REGULAR',
      'HDFC Bank', '9876543210', 'HDFC0001234',
      12000, '2025-01', 'GENERATED', '2025-02-01T10:05:00Z', null,
    ),

    // 3. Unregistered GST — no GST on invoice, Individual
    build(
      'inv-003', 3,
      'o7', 'O7', 'Patel Provision Store', 'Patel Stores', 'Ankit Patel',
      '9876500002',
      'Gujarat',
      'ATNPP9876C', null,
      'INDIVIDUAL', 'UNREGISTERED',
      'Axis Bank', '1122334455', 'UTIB0001234',
      3500, '2025-01', 'GENERATED', '2025-02-01T10:10:00Z', null,
    ),

    // 4. No PAN — 20% TDS internally, Firm
    build(
      'inv-004', 4,
      'o11', 'O11', 'Kumar General Mart', 'Kumar Brothers', 'Vijay Kumar',
      '9876500003',
      'Delhi',
      null, null,
      'FIRM', 'UNREGISTERED',
      'Punjab National Bank', '6677889900', 'PUNB0001234',
      2000, '2025-01', 'GENERATED', '2025-02-01T10:15:00Z', null,
    ),

    // 5. Composite GST — no GST on invoice, Individual, WB
    build(
      'inv-005', 5,
      'o1', 'O1', 'Singh Kirana Corner', 'Singh Traders', 'Harpreet Singh',
      '9876500004',
      'West Bengal',
      'BFLPS4567G', null,
      'INDIVIDUAL', 'COMPOSITE',
      'Bank of India', '5544332211', 'BKID0001234',
      4200, '2025-01', 'PAID', '2025-02-01T10:20:00Z', '2025-02-18T09:00:00Z',
    ),
  ];
})();

/** Look up a single mock invoice by id */
export function getMockInvoice(id: string): VisibilityInvoice | undefined {
  return MOCK_VISIBILITY_INVOICES.find((inv) => inv.id === id);
}

/** Look up mock invoices for a specific outlet */
export function getMockInvoicesForOutlet(outletId: string): VisibilityInvoice[] {
  return MOCK_VISIBILITY_INVOICES.filter((inv) => inv.outletId === outletId);
}
