import { getTenantConfig } from '@/lib/platform/server';
import { pwaAppName, type PwaScope } from '@/lib/pwa/manifest';

/**
 * PwaHead — drops the PWA install metadata into the document <head>.
 *
 * Self-contained SERVER component: it resolves the tenant itself via
 * getTenantConfig(), so the orchestrator only needs `<PwaHead scope="sales" />`.
 * The orchestrator gates which scope to render based on the request path
 * (/sales vs /partner).
 *
 * React 19 hoists bare <link>/<meta> elements to <head>, so these render
 * correctly even though this component is mounted in the layout tree.
 *
 * Provides:
 *  - <link rel="manifest"> → the per-tenant manifest route handler for the scope.
 *  - iOS install meta (Apple has no manifest support) + the apple-touch-icon.
 *
 * Icon assets live at /icons/<slug>/… and are generated by another stream.
 * Viewport / safe-area (`viewport-fit=cover`) is owned by the root layout's
 * `viewport` export — intentionally NOT set here.
 */
export default async function PwaHead({ scope }: { scope: PwaScope }) {
  const config = await getTenantConfig();
  const slug = config.slug;
  const title = pwaAppName(config, scope);

  return (
    <>
      <link rel="manifest" href={`/${scope}/manifest.webmanifest`} />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta
        name="apple-mobile-web-app-status-bar-style"
        content="black-translucent"
      />
      <meta name="apple-mobile-web-app-title" content={title} />
      <link
        rel="apple-touch-icon"
        href={`/icons/${slug}/apple-touch-icon-180.png`}
      />
    </>
  );
}
