-- Migration: add Client (tenant) table + ClientStatus enum (task 1.3, gap #22)
-- Generated by `prisma migrate diff` (Prisma 7). Purely additive — no ALTER/DROP.
-- Applied to dev DB (gifsy_dev) via the Cloud SQL Auth Proxy on 2026-06-15.
-- NOTE: this dev DB is db-push/manual-SQL managed (no _prisma_migrations history),
-- so we apply the diff SQL directly rather than `prisma migrate dev` (which would reset).

-- CreateEnum
CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'ONBOARDING');

-- CreateTable
CREATE TABLE "clients" (
    "id" TEXT NOT NULL,
    "internalName" TEXT NOT NULL,
    "status" "ClientStatus" NOT NULL,
    "onboardedAt" TIMESTAMP(3) NOT NULL,
    "branding" JSONB NOT NULL,
    "features" JSONB NOT NULL,
    "partnerClasses" JSONB NOT NULL,
    "approvalHierarchy" JSONB NOT NULL,
    "notifications" JSONB NOT NULL,
    "invoicing" JSONB NOT NULL,
    "wallet" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);
