-- Migration: add clientId + lastSeenAt to user_sessions (task 1.2/1.8 — S1)
-- Generated by `prisma migrate diff` (Prisma 7). Purely additive.
-- Safe: user_sessions is empty (UserSession was never written before sessions work).
-- Applied to dev (gifsy_dev) via diff-SQL under a current_database guard — NOT `prisma migrate dev`.

-- AlterTable
ALTER TABLE "user_sessions" ADD COLUMN     "clientId" TEXT NOT NULL,
ADD COLUMN     "lastSeenAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "user_sessions_clientId_idx" ON "user_sessions"("clientId");
