/**
 * Shared PWA manifest helpers.
 *
 * The installable shell is scoped to a single portal (`sales` or `partner`) so
 * the installed app can't navigate into /admin or /gifsy. Branding (name,
 * colours, icons) is resolved per-tenant from the same ClientConfig the rest of
 * the app uses (via getTenantConfig), so each tenant installs its own branded app.
 *
 * Icon assets are generated by another stream and served statically from
 * /icons/<slug>/… (the proxy excludes /icons/ from rewrites). This file only
 * references those paths — it does not generate them.
 */

import type { MetadataRoute } from 'next';
import type { ClientConfig } from '@/lib/platform/client-config';

export type PwaScope = 'sales' | 'partner';

/**
 * App name shown on the home screen / install prompt, per portal.
 *   sales   → "<displayName> Sales"
 *   partner → "<displayName>"
 */
export function pwaAppName(config: ClientConfig, scope: PwaScope): string {
  const name = config.branding.displayName;
  return scope === 'sales' ? `${name} Sales` : name;
}

/**
 * Builds the per-tenant, per-portal Web App Manifest object.
 * `display: 'standalone'` + a scoped `scope`/`start_url` make it installable and
 * confined to /sales (or /partner).
 */
export function buildManifest(
  config: ClientConfig,
  scope: PwaScope,
): MetadataRoute.Manifest {
  const slug = config.slug;
  const color = config.branding.primaryColor;
  const base = `/${scope}`;
  const name = pwaAppName(config, scope);

  return {
    id: base,
    name,
    short_name: name,
    start_url: base,
    scope: base,
    display: 'standalone',
    theme_color: color,
    background_color: color,
    icons: [
      {
        src: `/icons/${slug}/icon-192.png`,
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: `/icons/${slug}/icon-512.png`,
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: `/icons/${slug}/icon-maskable-512.png`,
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
