'use client';

/**
 * /partner/invoices — Retailer's invoice list
 * Shows gross amount only. No TDS, no 194C, no tax breakdown.
 * Dismissible info banner explaining self-billing.
 */

import { useState } from 'react';
import Link from 'next/link';
import {
  FileText,
  ChevronRight,
  Info,
  X,
  CheckCircle,
  Clock,
} from 'lucide-react';
import { MOCK_VISIBILITY_INVOICES } from '@/lib/invoice';
import { DEMO_SESSIONS } from '@/lib/partner-session';

// ── Demo: use SSS demo session outlet ────────────────────────────────────────
const SESSION = DEMO_SESSIONS['SSS'];

// Demo retailer is o2 in mock data
const DEMO_OUTLET_ID = SESSION.outletId; // 'o2'
const partnerInvoices = MOCK_VISIBILITY_INVOICES.filter(
  (inv) => inv.outletId === DEMO_OUTLET_ID
);

// ── Helpers ───────────────────────────────────────────────────────────────────
const STATUS_STYLES = {
  GENERATED: 'bg-amber-50 text-amber-700',
  PAID: 'bg-green-50 text-green-700',
};
const STATUS_LABEL = {
  GENERATED: 'Processing',
  PAID: 'Paid',
};

export default function PartnerInvoiceListPage() {
  const [bannerDismissed, setBannerDismissed] = useState(false);

  return (
    <div className="space-y-4 fade-in">
      {/* Header */}
      <div>
        <h1 className="text-base font-bold text-gray-900">My Invoices</h1>
        <p className="text-xs text-gray-500 mt-0.5">
          Visibility service invoices raised on your behalf
        </p>
      </div>

      {/* Info banner — dismissible */}
      {!bannerDismissed && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex gap-3">
          <Info className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
          <div className="flex-1 text-xs text-blue-700">
            <p className="font-semibold mb-0.5">About your invoices</p>
            <p>
              These invoices are automatically generated by Tech Gifsy Solutions Limited on
              your behalf for marketing visibility services you have provided. No signature
              is required. Please download and retain these for your records.
            </p>
          </div>
          <button
            onClick={() => setBannerDismissed(true)}
            className="text-blue-400 hover:text-blue-600 flex-shrink-0"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Invoice list */}
      {partnerInvoices.length === 0 ? (
        <div className="bg-white border border-gray-200 rounded-xl py-16 flex flex-col items-center gap-3 text-gray-400">
          <FileText className="w-10 h-10" />
          <p className="text-sm font-medium">No invoices yet</p>
          <p className="text-xs">Invoices will appear here once payouts are approved.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {partnerInvoices.map((inv) => (
            <Link
              key={inv.id}
              href={`/partner/invoices/${inv.id}`}
              className="block bg-white border border-gray-200 rounded-xl p-4 hover:shadow-sm transition-shadow"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  {/* Invoice number */}
                  <p className="text-[11px] font-mono text-gray-400 truncate">{inv.invoiceNumber}</p>
                  {/* Period + description */}
                  <p className="text-sm font-semibold text-gray-800 mt-0.5">{inv.periodLabel}</p>
                  <p className="text-xs text-gray-500 mt-0.5 truncate">{inv.description}</p>
                </div>
                <div className="flex flex-col items-end gap-1.5 flex-shrink-0">
                  {/* Gross amount — this is what the retailer sees */}
                  <p className="text-base font-bold text-gray-900">
                    ₹{inv.baseAmount.toLocaleString('en-IN')}
                  </p>
                  <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full flex items-center gap-1 ${STATUS_STYLES[inv.status]}`}>
                    {inv.status === 'PAID'
                      ? <CheckCircle className="w-2.5 h-2.5" />
                      : <Clock className="w-2.5 h-2.5" />
                    }
                    {STATUS_LABEL[inv.status]}
                  </span>
                </div>
                <ChevronRight className="w-4 h-4 text-gray-300 flex-shrink-0 self-center" />
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
